version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps):"
      prefix-development: "build(deps-dev):"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
