name: semantic-versioning
version: 1.0.0
description: Semantic release support for tagging `spinnaker-pipeline-trigger` with semantic versioning.
repository:
  type: git
  url: https://github.com/ExpediaGroup/spinnaker-pipeline-trigger
keywords: []
author: ""
license: ISC
devDependencies:
  semantic-release: ^17.4.4
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: angular
      releaseRules:
        - breaking: true
          release: major
        - type: breaking
          release: major
        - type: docs
          release: patch
        - type: refactor
          release: patch
        - scope: no-release
          release: false
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - - "@semantic-release/exec"
    - "prepareCmd": "yarn build && yarn package"
  - - "@semantic-release/git"
    - "assets":
        - "dist/**/*.{js,js.map}"
      "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
release:
  branches:
    - main
branches:
  - main
