---
name: Release
on:
  push:
    branches:
      - main

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: release
        name: Run release please
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
      - if: steps.release.outputs.releases_created
        name: Trigger Publish
        uses: actions/github-script@v6
        with:
          github-token: ${{ (secrets.github-token != '' && secrets.github-token) || secrets.GITHUB_TOKEN }}
          retries: 3
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'publish.yaml',
              ref: '${{ steps.release.outputs.tag_name }}'
            })
