name: "Test"
on:
  pull_request:
    branches:
      - main

jobs:
  test: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: "12"
      - run: |
          yarn
      - run: |
          yarn all
