name: "Test"
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  test: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - run: |
          yarn
      - run: |
          yarn all
      - name: Create a file for test push
        run: touch dist/test.txt
      - name: Check for diff
        id: diff
        run: echo "::set-output name=GIT_DIFF::$(git diff --name-only dist/)"
      - name: Push build
        if: ${{ steps.diff.outputs.GIT_DIFF != '' }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add dist/*
          git commit -m "chore: Build Source"
          git push origin HEAD:${{ github.head_ref }}
