---
name: "Test"
on:
  pull_request:
    branches:
      - main

jobs:
  test: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: |
          yarn
      - run: |
          yarn all
      - name: Check for diff
        id: diff
        run: |
          git status -s dist/ | grep "dist/" || echo "SHOULD_PUSH_BUILD=false" >> "$GITHUB_OUTPUT
          echo "SHOULD_PUSH_BUILD=true" >> "$GITHUB_OUTPUT"
      - name: Push build
        if: ${{ steps.diff.outputs.SHOULD_PUSH_BUILD == 'true' }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add dist/*
          git commit -m "chore: Build Source"
          git push
